USE DATABASE ANIME_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_ANIME (
    INGEST_ID   STRING,
    FETCHED_AT  TIMESTAMP_LTZ,
    PAGE        INTEGER,
    SIZE        INTEGER,
    RESPONSE    VARIANT
);
